
version: '3.8'

services:
  solana_rust_app:
    build: .
    volumes:
      - .:/usr/src/app
      - cargo-git:/usr/src/app/.cargo/git
      - cargo-registry:/usr/src/app/.cargo/registry
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: cargo watch -x run

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  cargo-git:
  cargo-registry:
  postgres_data:
